const { Engine, World, Bodies, Body, Events } = Matter;
const canvas=document.getElementById('game'),wrap=document.getElementById('gameWrap'),dropBtn=document.getElementById('dropBtn'),restartBtn=document.getElementById('restartBtn'),ballCountEl=document.getElementById('ballCount'),collectedEl=document.getElementById('collected'),statusEl=document.getElementById('status');
let engine,ctx,W=420,H=720,balls=new Set(),items=[],selected=null,collected=0,dropped=false,raf,lastTime=performance.now(),launcherX=210,drag=null;
const R=7,N=5,MAX=500,LY=58,SP=18;
const C={bg1:'#161e33',bg2:'#0a0e18',wall:'#4a536b',ball:'#fff',outline:'#111826',gate2:'#f4aa24',gate3:'#7a5cff',gate5:'#69b929',jump:'#24b8e7',bucket:'#222838',pin:'#78849f'};
function resize(){const r=wrap.getBoundingClientRect(),d=Math.max(1,Math.min(2,devicePixelRatio||1));canvas.width=r.width*d;canvas.height=r.height*d;canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);W=r.width;H=r.height;launcherX=Math.max(60,Math.min(W-60,launcherX||W/2));}
function ball(x,y,vx=0,vy=0){if(balls.size>=MAX)return;const b=Bodies.circle(x,y,R,{restitution:.35,friction:.005,frictionAir:.0015,density:.0018,label:'ball'});b.plugin={gateCooldown:0,jumpCooldown:0};Body.setVelocity(b,{x:vx,y:vy});balls.add(b);World.add(engine.world,b);hud();}
function removeBall(b){if(!balls.has(b))return;balls.delete(b);World.remove(engine.world,b);hud();}
function makeBody(it){let b;if(it.type==='pin')b=Bodies.circle(it.x,it.y,it.r,{isStatic:true,label:'pin'});else if(it.type==='wall')b=Bodies.rectangle(it.x,it.y,it.w,it.h,{isStatic:true,angle:it.angle,label:'wall'});else b=Bodies.rectangle(it.x,it.y,it.w,it.h,{isStatic:true,isSensor:true,label:it.type==='collector'?'collector':it.type==='jump'?'jump':'gate'});b.editorItem=it;if(it.mult)b.multiplier=it.mult;if(it.type==='jump')b.jumpPower=9;it.body=b;World.add(engine.world,b);}
function rebuild(it){if(it.body)World.remove(engine.world,it.body);makeBody(it);}
function addItem(type,x=W/2,y=H/2){let it;if(type==='wall')it={type,x,y,w:130,h:12,angle:0};else if(type==='pin')it={type,x,y,r:10};else if(type==='jump')it={type,x,y,w:130,h:38};else if(type==='collector')it={type,x,y,w:180,h:45};else it={type:'gate',x,y,w:130,h:38,mult:+type};items.push(it);makeBody(it);selected=it;statusEl.textContent='DRAG TO MOVE';}
function clearItems(){for(const it of items)if(it.body)World.remove(engine.world,it.body);items=[];selected=null;}
function setup(){if(raf)cancelAnimationFrame(raf);resize();engine=Engine.create({gravity:{x:0,y:1,scale:.00135}});balls=new Set();collected=0;dropped=false;collectedEl.textContent='0';dropBtn.style.display='block';dropBtn.disabled=false;statusEl.textContent='EDIT MODE';launcherX=W/2;clearItems();Events.on(engine,'collisionStart',collide);lastTime=performance.now();loop(lastTime);hud();}
function resetBalls(){for(const b of [...balls])removeBall(b);collected=0;collectedEl.textContent='0';dropped=false;dropBtn.style.display='block';dropBtn.disabled=false;statusEl.textContent='EDIT MODE';hud();}
function dropBalls(){if(dropped)return;dropped=true;selected=null;dropBtn.style.display='none';statusEl.textContent='PLAYING';for(let i=0;i<N;i++)ball(launcherX+(i-2)*SP,LY,(i-2)*.05,0);}
function collide(e){for(const p of e.pairs){const a=p.bodyA,b=p.bodyB,bl=a.label==='ball'?a:b.label==='ball'?b:null,o=bl===a?b:a;if(!bl)continue;if(o.label==='gate')multiply(bl,o.multiplier);if(o.label==='jump'){const n=performance.now();if(!bl.plugin.jumpCooldown||n>bl.plugin.jumpCooldown){Body.setVelocity(bl,{x:bl.velocity.x,y:-Math.abs(o.jumpPower||9)});bl.plugin.jumpCooldown=n+700;}}if(o.label==='collector'){collected++;removeBall(bl);collectedEl.textContent=collected;}}}
function multiply(b,m){const n=performance.now();if(b.plugin.gateCooldown&&n<b.plugin.gateCooldown)return;const x=b.position.x,y=b.position.y,vx=b.velocity.x,vy=Math.max(1.5,b.velocity.y);removeBall(b);const count=Math.min(m,MAX-balls.size);for(let i=0;i<count;i++){const s=(i-(count-1)/2)*4.5,nb=ball(x+s,y+10,vx+s*.045,vy+Math.random()*.25);if(nb)nb.plugin.gateCooldown=n+350;}}
function hud(){ballCountEl.textContent=dropped?balls.size:N;if(dropped&&balls.size===0)statusEl.textContent=`FINISHED ${collected}`;}
function rr(x,y,w,h,r,c){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=c;ctx.fill();}
function drawItem(it){ctx.save();if(it.type==='pin'){ctx.beginPath();ctx.arc(it.x,it.y,it.r,0,Math.PI*2);ctx.fillStyle=C.pin;ctx.fill();}else if(it.type==='wall'){ctx.translate(it.x,it.y);ctx.rotate(it.angle);ctx.fillStyle=C.wall;ctx.fillRect(-it.w/2,-it.h/2,it.w,it.h);}else{const col=it.type==='jump'?C.jump:it.type==='collector'?C.bucket:it.mult===5?C.gate5:it.mult===3?C.gate3:C.gate2;rr(it.x-it.w/2,it.y-it.h/2,it.w,it.h,8,col);ctx.fillStyle='#fff';ctx.font='900 24px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(it.type==='jump'?'⇈':it.type==='collector'?'COLLECT':'×'+it.mult,it.x,it.y);}if(selected===it&&!dropped){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.setLineDash([5,4]);const w=it.type==='pin'?it.r*2+14:it.w+14,h=it.type==='pin'?it.r*2+14:it.h+14;ctx.strokeRect(it.x-w/2,it.y-h/2,w,h);}ctx.restore();}
function draw(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,C.bg1);g.addColorStop(1,C.bg2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let x=20;x<W;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=20;y<H;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const it of items)drawItem(it);for(const b of balls){ctx.beginPath();ctx.arc(b.position.x,b.position.y,R,0,Math.PI*2);ctx.fillStyle=C.ball;ctx.fill();ctx.strokeStyle=C.outline;ctx.lineWidth=2;ctx.stroke();}if(!dropped){for(let i=0;i<N;i++){ctx.beginPath();ctx.arc(launcherX+(i-2)*SP,LY,R,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=C.outline;ctx.stroke()}ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='800 10px Arial';ctx.textAlign='center';ctx.fillText('↔ DRAG BALLS',launcherX,LY+28);}}
function loop(n){const d=Math.min(33,n-lastTime);lastTime=n;Engine.update(engine,d);for(const b of [...balls])if(b.position.y>H+100||b.position.x<-100||b.position.x>W+100)removeBall(b);draw();raf=requestAnimationFrame(loop);}
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
function hit(x,y){for(let i=items.length-1;i>=0;i--){const it=items[i];if(it.type==='pin'){if(Math.hypot(x-it.x,y-it.y)<it.r+12)return it;}else if(Math.abs(x-it.x)<it.w/2+8&&Math.abs(y-it.y)<it.h/2+12)return it;}return null;}
canvas.addEventListener('pointerdown',e=>{if(dropped)return;const p=pos(e),h=hit(p.x,p.y);if(h){selected=h;drag={kind:'item',dx:p.x-h.x,dy:p.y-h.y};}else if(p.y<120){selected=null;drag={kind:'launcher'};launcherX=Math.max(55,Math.min(W-55,p.x));}else selected=null;canvas.setPointerCapture?.(e.pointerId);e.preventDefault();});
canvas.addEventListener('pointermove',e=>{if(dropped||!drag)return;const p=pos(e);if(drag.kind==='launcher')launcherX=Math.max(55,Math.min(W-55,p.x));else if(selected){selected.x=Math.max(15,Math.min(W-15,p.x-drag.dx));selected.y=Math.max(15,Math.min(H-15,p.y-drag.dy));rebuild(selected);}e.preventDefault();});
canvas.addEventListener('pointerup',e=>{drag=null;canvas.releasePointerCapture?.(e.pointerId)});canvas.addEventListener('pointercancel',()=>drag=null);
document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{if(!dropped)addItem(b.dataset.add)}));
document.getElementById('rotateBtn').addEventListener('click',()=>{if(selected&&selected.type==='wall'&&!dropped){selected.angle+=Math.PI/12;rebuild(selected);}});
document.getElementById('deleteBtn').addEventListener('click',()=>{if(selected&&!dropped){World.remove(engine.world,selected.body);items=items.filter(x=>x!==selected);selected=null;}});
document.getElementById('clearBtn').addEventListener('click',()=>{if(!dropped){clearItems();statusEl.textContent='EMPTY';}});
dropBtn.addEventListener('click',dropBalls);restartBtn.addEventListener('click',resetBalls);window.addEventListener('resize',()=>{resize();});setup();